name: Bug Report
description: Report a bug in xueqiu_api
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback
      description: Paste logs/traceback here (please redact cookies/tokens).
      placeholder: |
        ```log
        ...
        ```
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Helpful details for debugging.
      placeholder: |
        - OS:
        - Python:
        - xueqiu_api version:
        - httpx version:
        - pydantic version:
    validations:
      required: true

